import React from 'react';
import { Download, Play, Award, DollarSign, BookOpen } from 'lucide-react';
export const DeveloperOnboarding = ({
  onComplete
}: {
  onComplete: () => void;
}) => {
  return <div className="max-w-lg mx-auto">
      <div className="text-center mb-8">
        <h2 className="text-2xl font-bold text-gray-900 mb-2">
          Welcome to the BotJob.ai Developer Platform!
        </h2>
        <p className="text-gray-600">
          Your application has been approved. Let's get you started building
          amazing AI agents.
        </p>
      </div>
      <div className="mb-8">
        <div className="aspect-w-16 aspect-h-9 mb-4">
          <div className="w-full h-64 bg-gray-200 rounded-lg flex items-center justify-center">
            <Play className="h-16 w-16 text-indigo-600" />
            <span className="sr-only">Play welcome video</span>
          </div>
        </div>
        <p className="text-sm text-gray-500 text-center">
          Watch our welcome video to learn about the platform
        </p>
      </div>
      <div className="space-y-6 mb-8">
        <div className="bg-white border border-gray-200 rounded-lg p-6 hover:shadow-md transition">
          <div className="flex items-start">
            <div className="flex-shrink-0">
              <Download className="h-6 w-6 text-indigo-600" />
            </div>
            <div className="ml-4">
              <h3 className="text-lg font-medium text-gray-900">
                SDK & Development Tools
              </h3>
              <p className="mt-1 text-sm text-gray-600">
                Download our SDK and development tools to start building AI
                agents.
              </p>
              <div className="mt-3">
                <button className="px-4 py-2 bg-indigo-600 text-white rounded-md text-sm font-medium hover:bg-indigo-700 transition">
                  Download SDK
                </button>
              </div>
            </div>
          </div>
        </div>
        <div className="bg-white border border-gray-200 rounded-lg p-6 hover:shadow-md transition">
          <div className="flex items-start">
            <div className="flex-shrink-0">
              <BookOpen className="h-6 w-6 text-indigo-600" />
            </div>
            <div className="ml-4">
              <h3 className="text-lg font-medium text-gray-900">
                First Agent Tutorial
              </h3>
              <p className="mt-1 text-sm text-gray-600">
                Follow our step-by-step guide to create your first AI agent in
                under 30 minutes.
              </p>
              <div className="mt-3">
                <button className="px-4 py-2 bg-indigo-600 text-white rounded-md text-sm font-medium hover:bg-indigo-700 transition">
                  Start Tutorial
                </button>
              </div>
            </div>
          </div>
        </div>
        <div className="bg-white border border-gray-200 rounded-lg p-6 hover:shadow-md transition">
          <div className="flex items-start">
            <div className="flex-shrink-0">
              <Award className="h-6 w-6 text-indigo-600" />
            </div>
            <div className="ml-4">
              <h3 className="text-lg font-medium text-gray-900">
                Certification Program
              </h3>
              <p className="mt-1 text-sm text-gray-600">
                Complete our certification program to become a verified
                BotJob.ai developer and unlock premium features.
              </p>
              <div className="mt-3">
                <button className="px-4 py-2 border border-indigo-600 text-indigo-600 rounded-md text-sm font-medium hover:bg-indigo-50 transition">
                  View Requirements
                </button>
              </div>
            </div>
          </div>
        </div>
        <div className="bg-white border border-gray-200 rounded-lg p-6 hover:shadow-md transition">
          <div className="flex items-start">
            <div className="flex-shrink-0">
              <DollarSign className="h-6 w-6 text-indigo-600" />
            </div>
            <div className="ml-4">
              <h3 className="text-lg font-medium text-gray-900">
                Revenue Sharing
              </h3>
              <p className="mt-1 text-sm text-gray-600">
                You earn 80% of all revenue generated by your AI agents.
                Payments are processed monthly with detailed analytics.
              </p>
              <div className="mt-3">
                <button className="px-4 py-2 border border-indigo-600 text-indigo-600 rounded-md text-sm font-medium hover:bg-indigo-50 transition">
                  Revenue Details
                </button>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div className="mt-8 text-center">
        <button onClick={onComplete} className="px-8 py-3 bg-indigo-600 text-white rounded-lg font-medium hover:bg-indigo-700 transition">
          Go to Developer Dashboard
        </button>
      </div>
    </div>;
};