export interface Database {
  public: {
    Tables: {
      users: {
        Row: {
          id: string;
          email: string;
          user_type: 'business' | 'developer' | 'admin';
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          email: string;
          user_type: 'business' | 'developer' | 'admin';
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          email?: string;
          user_type?: 'business' | 'developer' | 'admin';
          created_at?: string;
          updated_at?: string;
        };
      };
      business_profiles: {
        Row: {
          id: string;
          user_id: string;
          company_name: string;
          industry: string | null;
          company_size: string | null;
          use_cases: string[] | null;
          budget_min: number | null;
          budget_max: number | null;
          phone: string | null;
          website: string | null;
          address: any | null;
          onboarding_completed: boolean;
          trial_ends_at: string | null;
          stripe_customer_id: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          company_name: string;
          industry?: string | null;
          company_size?: string | null;
          use_cases?: string[] | null;
          budget_min?: number | null;
          budget_max?: number | null;
          phone?: string | null;
          website?: string | null;
          address?: any | null;
          onboarding_completed?: boolean;
          trial_ends_at?: string | null;
          stripe_customer_id?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          company_name?: string;
          industry?: string | null;
          company_size?: string | null;
          use_cases?: string[] | null;
          budget_min?: number | null;
          budget_max?: number | null;
          phone?: string | null;
          website?: string | null;
          address?: any | null;
          onboarding_completed?: boolean;
          trial_ends_at?: string | null;
          stripe_customer_id?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      developer_profiles: {
        Row: {
          id: string;
          user_id: string;
          name: string;
          company_name: string | null;
          experience_level: 'beginner' | 'intermediate' | 'expert' | null;
          technical_background: string[] | null;
          portfolio_links: any | null;
          github_username: string | null;
          linkedin_url: string | null;
          website_url: string | null;
          bio: string | null;
          verified: boolean;
          verification_date: string | null;
          verification_notes: string | null;
          stripe_account_id: string | null;
          commission_rate: number;
          total_earnings: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          name: string;
          company_name?: string | null;
          experience_level?: 'beginner' | 'intermediate' | 'expert' | null;
          technical_background?: string[] | null;
          portfolio_links?: any | null;
          github_username?: string | null;
          linkedin_url?: string | null;
          website_url?: string | null;
          bio?: string | null;
          verified?: boolean;
          verification_date?: string | null;
          verification_notes?: string | null;
          stripe_account_id?: string | null;
          commission_rate?: number;
          total_earnings?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          name?: string;
          company_name?: string | null;
          experience_level?: 'beginner' | 'intermediate' | 'expert' | null;
          technical_background?: string[] | null;
          portfolio_links?: any | null;
          github_username?: string | null;
          linkedin_url?: string | null;
          website_url?: string | null;
          bio?: string | null;
          verified?: boolean;
          verification_date?: string | null;
          verification_notes?: string | null;
          stripe_account_id?: string | null;
          commission_rate?: number;
          total_earnings?: number;
          created_at?: string;
          updated_at?: string;
        };
      };
      agents: {
        Row: {
          id: string;
          developer_id: string;
          name: string;
          slug: string;
          description: string | null;
          tagline: string | null;
          avatar_url: string | null;
          category: string;
          sub_category: string | null;
          capabilities: string[];
          integrations: string[] | null;
          languages: string[];
          pricing_model: 'subscription' | 'usage' | 'outcome';
          base_price: number | null;
          usage_rates: any | null;
          setup_fee: number;
          free_trial_days: number;
          status: 'draft' | 'pending_review' | 'active' | 'suspended';
          version: string;
          performance_metrics: any;
          configuration_schema: any | null;
          required_integrations: string[] | null;
          tags: string[] | null;
          featured: boolean;
          published_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          developer_id: string;
          name: string;
          slug: string;
          description?: string | null;
          tagline?: string | null;
          avatar_url?: string | null;
          category: string;
          sub_category?: string | null;
          capabilities: string[];
          integrations?: string[] | null;
          languages?: string[];
          pricing_model: 'subscription' | 'usage' | 'outcome';
          base_price?: number | null;
          usage_rates?: any | null;
          setup_fee?: number;
          free_trial_days?: number;
          status?: 'draft' | 'pending_review' | 'active' | 'suspended';
          version?: string;
          performance_metrics?: any;
          configuration_schema?: any | null;
          required_integrations?: string[] | null;
          tags?: string[] | null;
          featured?: boolean;
          published_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          developer_id?: string;
          name?: string;
          slug?: string;
          description?: string | null;
          tagline?: string | null;
          avatar_url?: string | null;
          category?: string;
          sub_category?: string | null;
          capabilities?: string[];
          integrations?: string[] | null;
          languages?: string[];
          pricing_model?: 'subscription' | 'usage' | 'outcome';
          base_price?: number | null;
          usage_rates?: any | null;
          setup_fee?: number;
          free_trial_days?: number;
          status?: 'draft' | 'pending_review' | 'active' | 'suspended';
          version?: string;
          performance_metrics?: any;
          configuration_schema?: any | null;
          required_integrations?: string[] | null;
          tags?: string[] | null;
          featured?: boolean;
          published_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      agent_subscriptions: {
        Row: {
          id: string;
          business_id: string;
          agent_id: string;
          stripe_subscription_id: string | null;
          stripe_product_id: string | null;
          status: 'trialing' | 'active' | 'cancelled' | 'past_due';
          current_period_start: string | null;
          current_period_end: string | null;
          cancel_at_period_end: boolean;
          cancelled_at: string | null;
          trial_end: string | null;
          metadata: any | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          business_id: string;
          agent_id: string;
          stripe_subscription_id?: string | null;
          stripe_product_id?: string | null;
          status?: 'trialing' | 'active' | 'cancelled' | 'past_due';
          current_period_start?: string | null;
          current_period_end?: string | null;
          cancel_at_period_end?: boolean;
          cancelled_at?: string | null;
          trial_end?: string | null;
          metadata?: any | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          business_id?: string;
          agent_id?: string;
          stripe_subscription_id?: string | null;
          stripe_product_id?: string | null;
          status?: 'trialing' | 'active' | 'cancelled' | 'past_due';
          current_period_start?: string | null;
          current_period_end?: string | null;
          cancel_at_period_end?: boolean;
          cancelled_at?: string | null;
          trial_end?: string | null;
          metadata?: any | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      agent_instances: {
        Row: {
          id: string;
          subscription_id: string;
          instance_name: string;
          configuration: any;
          phone_number: string | null;
          phone_number_sid: string | null;
          email_address: string | null;
          calendar_id: string | null;
          webhook_url: string | null;
          api_key: string;
          status: 'active' | 'paused' | 'training';
          last_active_at: string | null;
          training_completed_at: string | null;
          metadata: any | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          subscription_id: string;
          instance_name: string;
          configuration?: any;
          phone_number?: string | null;
          phone_number_sid?: string | null;
          email_address?: string | null;
          calendar_id?: string | null;
          webhook_url?: string | null;
          api_key?: string;
          status?: 'active' | 'paused' | 'training';
          last_active_at?: string | null;
          training_completed_at?: string | null;
          metadata?: any | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          subscription_id?: string;
          instance_name?: string;
          configuration?: any;
          phone_number?: string | null;
          phone_number_sid?: string | null;
          email_address?: string | null;
          calendar_id?: string | null;
          webhook_url?: string | null;
          api_key?: string;
          status?: 'active' | 'paused' | 'training';
          last_active_at?: string | null;
          training_completed_at?: string | null;
          metadata?: any | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      usage_logs: {
        Row: {
          id: string;
          instance_id: string;
          usage_type: 'call' | 'email' | 'task' | 'api';
          duration_seconds: number | null;
          quantity: number;
          metadata: any | null;
          cost: number | null;
          billed: boolean;
          created_at: string;
        };
        Insert: {
          id?: string;
          instance_id: string;
          usage_type: 'call' | 'email' | 'task' | 'api';
          duration_seconds?: number | null;
          quantity?: number;
          metadata?: any | null;
          cost?: number | null;
          billed?: boolean;
          created_at?: string;
        };
        Update: {
          id?: string;
          instance_id?: string;
          usage_type?: 'call' | 'email' | 'task' | 'api';
          duration_seconds?: number | null;
          quantity?: number;
          metadata?: any | null;
          cost?: number | null;
          billed?: boolean;
          created_at?: string;
        };
      };
      activity_logs: {
        Row: {
          id: string;
          instance_id: string;
          activity_type: string;
          activity_data: any;
          success: boolean;
          error_message: string | null;
          duration_ms: number | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          instance_id: string;
          activity_type: string;
          activity_data: any;
          success?: boolean;
          error_message?: string | null;
          duration_ms?: number | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          instance_id?: string;
          activity_type?: string;
          activity_data?: any;
          success?: boolean;
          error_message?: string | null;
          duration_ms?: number | null;
          created_at?: string;
        };
      };
      reviews: {
        Row: {
          id: string;
          agent_id: string;
          business_id: string;
          rating: number;
          title: string | null;
          comment: string | null;
          pros: string | null;
          cons: string | null;
          developer_response: string | null;
          developer_response_at: string | null;
          helpful_count: number;
          verified_purchase: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          agent_id: string;
          business_id: string;
          rating: number;
          title?: string | null;
          comment?: string | null;
          pros?: string | null;
          cons?: string | null;
          developer_response?: string | null;
          developer_response_at?: string | null;
          helpful_count?: number;
          verified_purchase?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          agent_id?: string;
          business_id?: string;
          rating?: number;
          title?: string | null;
          comment?: string | null;
          pros?: string | null;
          cons?: string | null;
          developer_response?: string | null;
          developer_response_at?: string | null;
          helpful_count?: number;
          verified_purchase?: boolean;
          created_at?: string;
          updated_at?: string;
        };
      };
      invoices: {
        Row: {
          id: string;
          business_id: string;
          stripe_invoice_id: string | null;
          invoice_number: string | null;
          amount: number;
          tax: number;
          total: number;
          currency: string;
          status: string;
          due_date: string | null;
          paid_at: string | null;
          period_start: string | null;
          period_end: string | null;
          line_items: any | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          business_id: string;
          stripe_invoice_id?: string | null;
          invoice_number?: string | null;
          amount: number;
          tax?: number;
          total: number;
          currency?: string;
          status: string;
          due_date?: string | null;
          paid_at?: string | null;
          period_start?: string | null;
          period_end?: string | null;
          line_items?: any | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          business_id?: string;
          stripe_invoice_id?: string | null;
          invoice_number?: string | null;
          amount?: number;
          tax?: number;
          total?: number;
          currency?: string;
          status?: string;
          due_date?: string | null;
          paid_at?: string | null;
          period_start?: string | null;
          period_end?: string | null;
          line_items?: any | null;
          created_at?: string;
        };
      };
      team_members: {
        Row: {
          id: string;
          business_id: string;
          user_id: string;
          role: 'owner' | 'admin' | 'member';
          permissions: any;
          invited_by: string | null;
          invited_at: string;
          accepted_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          business_id: string;
          user_id: string;
          role?: 'owner' | 'admin' | 'member';
          permissions?: any;
          invited_by?: string | null;
          invited_at?: string;
          accepted_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          business_id?: string;
          user_id?: string;
          role?: 'owner' | 'admin' | 'member';
          permissions?: any;
          invited_by?: string | null;
          invited_at?: string;
          accepted_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      integrations: {
        Row: {
          id: string;
          business_id: string;
          service_name: string;
          configuration: any;
          encrypted_credentials: string | null;
          is_active: boolean;
          last_sync_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          business_id: string;
          service_name: string;
          configuration: any;
          encrypted_credentials?: string | null;
          is_active?: boolean;
          last_sync_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          business_id?: string;
          service_name?: string;
          configuration?: any;
          encrypted_credentials?: string | null;
          is_active?: boolean;
          last_sync_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      webhooks: {
        Row: {
          id: string;
          business_id: string;
          url: string;
          events: string[];
          secret: string;
          is_active: boolean;
          last_triggered_at: string | null;
          failure_count: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          business_id: string;
          url: string;
          events: string[];
          secret?: string;
          is_active?: boolean;
          last_triggered_at?: string | null;
          failure_count?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          business_id?: string;
          url?: string;
          events?: string[];
          secret?: string;
          is_active?: boolean;
          last_triggered_at?: string | null;
          failure_count?: number;
          created_at?: string;
          updated_at?: string;
        };
      };
      webhook_logs: {
        Row: {
          id: string;
          webhook_id: string;
          event_type: string;
          payload: any;
          response_status: number | null;
          response_body: string | null;
          attempts: number;
          success: boolean | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          webhook_id: string;
          event_type: string;
          payload: any;
          response_status?: number | null;
          response_body?: string | null;
          attempts?: number;
          success?: boolean | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          webhook_id?: string;
          event_type?: string;
          payload?: any;
          response_status?: number | null;
          response_body?: string | null;
          attempts?: number;
          success?: boolean | null;
          created_at?: string;
        };
      };
    };
    Views: {
      [_ in never]: never;
    };
    Functions: {
      [_ in never]: never;
    };
    Enums: {
      [_ in never]: never;
    };
  };
}